### PR TITLE
chore: load components using Main's ClassLoader

### PR DESCRIPTION
**Pull request by octonato**
This is in preparation for #1489.  

Not really needed for now but it is in any case a good measure to keep all project classes on the same loader. We never know which other tooling can be used by the users.

### CODE REVIEW

**Review by franciscolopezsancho — APPROVED** [review]
Looking at https://github.com/lightbend/kalix-jvm-sdk/issues/1489 it makes sense to me.

**Comment by franciscolopezsancho** [comment]
One question though.
> We never know which other tooling can be used by the users.
Could you elaborate?

**Comment by octonato** [comment]
> One question though.
> 
> > We never know which other tooling can be used by the users.
> 
> Could you elaborate?

Well, I don't know. I never now. 😄 

My thinking is that even if we are not yet supporting Spring dev tools, a user can add it themselves. Or they can try any other tooling that does a similar trick. The trick being: sneak somewhere in the bootstrap and create different classloader for code in the project. 

This is very unlikely though. Most probably people will try Spring dev-tools and hit some other issues because we are not yet ready for that.

**Comment by franciscolopezsancho** [comment]
I think I get the picture :) 👍

**Pull request merged**
