### PR TITLE
fix: Remove view id length restriction

### PR DESCRIPTION
**Pull request by patriknw**
* Reverts https://github.com/lightbend/akkaserverless-java-sdk/pull/866
* Release this after https://github.com/lightbend/kalix-proxy/pull/1370

### CODE REVIEW

**Comment by patriknw** [comment]
@johanandren Is there anything similar in the javascript-sdk? I can't see any such PR.

**Comment by johanandren** [comment]
I think I did it together with other work, I can revert over there.

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
(will need a proxy release/bump before CI passes though)

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
