### PR TITLE
chore: use docker compose instead of docker-compose

### PR DESCRIPTION
**Pull request by girdharshubham**

### CODE REVIEW

**Comment by franciscolopezsancho** [comment]
LGTM while I have an ask. 
Could you try removing your docker-compose binary? then go to the root of the `kalix-jvm-sdk` and `.publishLocally.sh`? So you build locally the SDK and later use that version in your project? Should take a handful of minutes. 
I did that on mac and it works, as expected.

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
LGTM, but I didn't understand @franciscolopezsancho request (or its motivation), so I'm waiting before merging.

**Comment by girdharshubham** [comment]
I think he means that I should test it locally first.

**Comment by girdharshubham** [comment]
I tried it by swapping the kalix sbt plugin with one built locally and then a `runAll`. Looks to be running

**Comment by efgpinto** [comment]
This will work out-of-the-box for anyone using Docker Desktop.

However, for someone like me using Colima and brew, I needed to follow [this advice](https://github.com/abiosoft/colima/discussions/874).

Just leaving this info here for future reference in case we get any user reporting a similar issue.

**Pull request merged**
