### PR TITLE
Update LICENSE to BSL

### PR DESCRIPTION
**Pull request by JustinPihony**

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
I was planning to cut a release today, but maybe we want to wait for this one to get it? 
Also, once we merge this, it will be good to bump akka version.

**Review by ennru — CHANGES_REQUESTED** [review]
More things needed.

**Comment by octonato** [comment]
We have a bunch of deprecated classes/APIs that we would like to remove. They are deprecated since 1.3.0 (or even before). 

As we move to BSL, I think we should bump the version to v1.5.0 and then it's a good opportunity to remove all the deprecated APIs we have.

**Comment by octonato** [comment]
I repointed this PR to `release-1.5.0` branch.

There are other PRs that we only want to merge on this release branch. As such we are free to release `main` if needed.

**Comment by octonato** [comment]
@ennru, is this ready to be merged into `release-1.5.0` branch?

**Review by ennru — APPROVED** [review]
LGTM for release with 1.5.0.

**Pull request merged**
