### PR TITLE
feat(scala): Support for building Kalix images on Mac m1 #78

### PR DESCRIPTION
**Pull request by johanandren**
References #78

A somewhat sketchy solution, but seems to work so maybe worth it?

If we decide it is, needs to be applied to all samples and the quickstart g8 template.

### CODE REVIEW

**Comment by johanandren** [comment]
@raboof what do you think about this somewhat hacky solution? (m1/arm64 needs a different docker command to cross build the image for amd64)

**Comment by raboof** [comment]
> @raboof what do you think about this somewhat hacky solution? (m1/arm64 needs a different docker command to cross build the image for amd64)

Yeah I think it makes sense. Would be neat if this could be an upstream feature of native-packager, where you would set the 'target architecture' (default 'inherit' or somesuch) and it'd do the right thing, but failing that this seems reasonable ;)

**Comment by raboof** [comment]
I guess we need something similar for javascript and the Maven plugin then? :/

**Comment by johanandren** [comment]
The maven plugin I have already solved m1 support for in #https://github.com/lightbend/kalix-jvm-sdk/pull/904 so it's only sbt we need to figure it out for.

Javascript is a whole different story with more blockers before docker becomes the main problem https://github.com/lightbend/kalix-javascript-sdk/issues/99

**Comment by johanandren** [comment]
Created an upstream issue/feature request for the plugin: https://github.com/sbt/sbt-native-packager/issues/1503

**Comment by johanandren** [comment]
I'll go ahead and copy this to the other samples and the g8 template then.

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
