### PR TITLE
bump: kalix-proxy 1.0.0-M4

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by johanandren** [comment]
Seems we missed something when renaming branches

**Comment by johanandren** [comment]
Nope, but something related to the new main branch for sure.

**Comment by ennru** [comment]
CircleCI even checks for the `kalix-sdk.version` in pom.xml and plugins.sbt of the samples.

**Comment by ennru** [comment]
Is this still pending, or was it done in another PR?

**Comment by raboof** [comment]
still pending, needed a close/reopen for CircleCI to figure out to test it against the new `main` it seems

**Comment by raboof** [comment]
> still pending, needed a close/reopen for CircleCI to figure out to test it against the new `main` it seems

hmm, seems that didn't help, amended the commit to kick of a completely new build

**Review by raboof — APPROVED** [review]

**Pull request merged**
