### PR TITLE
chore: build docker image on 'install'

### PR DESCRIPTION
**Pull request by octonato**
References https://github.com/lightbend/kalix-jvm-sdk/issues/1471

### CODE REVIEW

**Comment by octonato** [comment]
@franciscolopezsancho, this is now green. Failures were due to something else. Circle CI had also a notification in their UI saying that the services were degraded. Maybe that was the reason.

**Review by efgpinto — APPROVED** [review]
Interesting one.. Did this speed up the IT tests a bit or not really?

LGTM.

**Comment by octonato** [comment]
Yep, it gets a little better.

**Comment by franciscolopezsancho** [comment]
Sorry, I've been late. I was waiting for the CI to pass.

**Pull request merged**
