### PR TITLE
chore: Create a sample with extra docker containers (Tempo and Jaeger UI) to store (and show) traces.

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
References https://github.com/lightbend/kalix/issues/10288

### CODE REVIEW

**Comment by hedefalk** [comment]
Cool, I'll try it out!

**Comment by hedefalk** [comment]
Nice, works fine!

image


Maybe this Jaeger UI is a little harder to embed as nicely as the Control Tower Grafana stuff though. Did we tune that a lot or is the matching of styling more of luck?

**Comment by franciscolopezsancho** [comment]
We almost didn't tune it. Just removed a few references to Grafana here and there. It was more of luck.

**Review by hedefalk — APPROVED** [review]

**Comment by hedefalk** [comment]
I approve this Draft :)

**Comment by hedefalk** [comment]
I was probably a bit brainfogged yesterday ;)

Just realized - this has to be _per service_ anyway, right? The full reasoning above was me thinking about a single JaegerUI for potentially multiple services. 

Or would it be possible to have multiple services (and by that I mean Kalix services) pushing traces to the same tempo instance?

**Comment by franciscolopezsancho** [comment]
Thanks :). 
I don't think will merge it at the moment. I'm not sure we want to expose this.

**Comment by franciscolopezsancho** [comment]
This was just an examples. Useful though to see how to run this in local. Not meant to be merged.

**Pull request closed without merging**
