### PR TITLE
feat: adding file to show kalix SDK version

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
References https://github.com/lightbend/kalix-proxy/issues/786

### CODE REVIEW

**Comment by raboof** [comment]
Oops, it seems my merge didn't pick up the `feat: ` that should be in the commit title. Sorry :)

**Comment by franciscolopezsancho** [comment]
thanks for prompt merge 👍

**Comment by octonato** [comment]
> Oops, it seems my merge didn't pick up the `feat: ` that should be in the commit title. Sorry :)

If I remember correctly, if you do a squash merge it takes the title of the PR.

**Comment by pvlugter** [comment]
Let's not have a manually managed version string, but have it dynamically generated from the version tag (and so it will be automatically included on releases).

See the version attribute that's created:

https://github.com/lightbend/kalix-jvm-sdk/blob/bb1aee0731fcb005f7ba7359e3f435ffe5457dab/docs/Makefile#L33-L34

Can write a file to `${managed_attachments}` in the same way.

**Pull request merged**
