### PR TITLE
chore: Use regular text logs for dev mode instead of JSON

### PR DESCRIPTION
**Pull request by johanandren**
For the user function itself, proxy logs are a separate thing

### CODE REVIEW

**Comment by johanandren** [comment]
IT tests in samples looks like they already have a logback-text.xml present

**Comment by efgpinto** [comment]
So, for the spring ones I already have the logs not formatted in JSON without your changes.. which got me wondering what am I missing? or is the json format miss-configured for the spring ones actually and we never noticed?

Btw, this is a great improvement for DX I think. 👍

**Comment by octonato** [comment]
> For grpc sdks this works as expected but for the spring ones I already have the logs not formatted in JSON without your changes.. which got me wondering what am I missing? or is the json format miss-configured for the spring ones actually and we never noticed?
> 
> Btw, this is a great improvement for DX I think. 👍

Spring ones are using STDOUT, instead of JSON-STDOUT. Although the config is there.

**Review by octonato — APPROVED** [review]
LGTM

I will open another one to fix the Spring samples

**Pull request merged**
