### PR TITLE
chore: disciplined compiler settings and deprecation removal

### PR DESCRIPTION
**Pull request by octonato**
Configures compiler to fail in case of warnings

Remove a bunch on long due deprecation removals (targeting release 1.5.0)

* KalixTestKit.getGrpcClientSettings - since 0.8.1 in (7acafc31ad6c4789e5d073d143d58c818db50ad4)
* EntityOptions.withPassivationStrategy - since 1.1.4 in (46870e540abaeed56901b5f903c1e7fc9188ba93)
* EntityKey - since 1.3.0 in (0d3ae964cda4a9b9a377845a648d76a1d81d3ad9)
* EntityType - since 1.3.0 in (0d3ae964cda4a9b9a377845a648d76a1d81d3ad9)
* GenerateEntityKey - since 1.3.0 in (0d3ae964cda4a9b9a377845a648d76a1d81d3ad9)
* KalixTestKit.getTopic - since 1.3.4 in (80bbbfef753c367e6035bb3ab15f01114038d9a8)

TODO
- [ ] sbt plugin still emitting warnings - needs fix
- [ ] solution for deprecated scalab.compiler.DescriptorImplicits - our problem, not user facing

### CODE REVIEW

**Comment by octonato** [comment]
Removal of passivation strategy in 6b211cdd9259a6a733d4982577de3bcb07779f29 requires some extra thought though.

Passivation strategy was deprecated in https://github.com/lightbend/kalix-jvm-sdk/pull/1375 but only for ES and VE, not for replicated entities. The reason is that the runtime ignores this settings for ES and VE. 

Fair enough. This PR removes it from the ES and VE and keeps it for RE. But it raises the question if that's really what we want. Why this settings is ignored for ES and VE in the runtime?

**Comment by octonato** [comment]
@aludwiko, may I ask you to review that specific commit cad4b44370b0e9be13eb5a66d0ee883536748d00? 

This is about removing the Testkit Topic API. I just want to be sure that I wasn't overly enthusiastic on my deletes.

**Comment by aludwiko** [comment]
> @aludwiko, may I ask you to review that specific commit https://github.com/lightbend/kalix-jvm-sdk/commit/80bbbfef753c367e6035bb3ab15f01114038d9a8? 

All good!

**Review by aludwiko — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
I will merge it and tackle the open todos in follow-up PRs.

**Comment by franciscolopezsancho** [comment]
I was having a look in case you needed it. So far so good anyways. 

```
    KalixTestKit.getGrpcClientSettings - since 0.8.1 in (7acafc3) - x
    EntityOptions.withPassivationStrategy - since 1.1.4 in (46870e5) - x. Side question why `ReplicatedEntityOptions.withPassivationStrategy` still exists? 
    EntityKey - since 1.3.0 in (0d3ae96) - x
    EntityType - since 1.3.0 in (0d3ae96) - x 
    GenerateEntityKey - since 1.3.0 in (0d3ae96) - x 
    KalixTestKit.getTopic - since 1.3.4 in (80bbbfe)
```

Found `ReplicatedEntityOptions.withWriteConsistency` has a `@returns`. Feels like the most nitpicking imaginable.

In any case. You are a saint. Thanks for the PR.

**Comment by franciscolopezsancho** [comment]
> This should have been raised during the build...Each run raises new issues that should have been raised earlier.

Not nice.

> Don't put your money on that.

:) Too late

**Pull request merged**
