### PR TITLE
chore: logs in integration tests be plain text by default

### LINKED ISSUE #1676: Java sdk archetype not defaulting to plain text logs for Integration tests
Since we generate and example for an IntegrationTest we should also include the logback-test.xml file that makes the logs be in JSON format by default.

### PR DESCRIPTION
**Pull request by efgpinto**
Close #1676

### CODE REVIEW

**Review by aludwiko — APPROVED** [review]

**Review by octonato — APPROVED** [review]
LGTM

Can you also add this file to the Kotlin template?

**Comment by efgpinto** [comment]
> Can you also add this file to the Kotlin template?

Added for kotlin template now.

> I just saw that we have it in src/test/resources in the protobuf templates, but we also need it in src/it/resources.

We just need it in one place I think. For code-first I put in the IT folder because we generate a sample test there by default (but could move it to `test`folder if you think it's better). For protocol-first, the one we have under `test` is also picked up when running integration tests. Thus, I'm not sure we necessarily need to have them in both places, do we?

**Comment by octonato** [comment]
> Thus, I'm not sure we necessarily need to have them in both places, do we?

It depends if the IntegrationTest includes the Test resources. From what you describe, it seems it does.

**Comment by efgpinto** [comment]
> > Thus, I'm not sure we necessarily need to have them in both places, do we?
> 
> It depends if the IntegrationTest includes the Test resources. From what you describe, it seems it does.

It does with this PR for code-first sdk. For protobuf, we have it under `test`. There is no specific folder for integration tests.

**Comment by efgpinto** [comment]
I will merge this now and follow up if needed.

**Pull request merged**
