### PR TITLE
fix(sample): run kafka sample locally with kafka

### PR DESCRIPTION
**Pull request by raboof**
Probably also needs changes in the circleci config

Refs #851

### CODE REVIEW

**Comment by franciscolopezsancho** [comment]
We could delete this file and only use what's in the kafka folder to start the proxy, Kafka and zookeeper? It might not be easy to spot in the README.md that `docker compose up` is supposed to run from within the `./kafka` folder.

**Comment by raboof** [comment]
> It might not be easy to spot in the README.md that `docker compose up` is supposed to run from within the `./kafka` folder.

Ah, indeed I completely missed that :D

**Comment by raboof** [comment]
> Probably also needs changes in the circleci config

ah, looking closer we don't seem to test this sample in CI at all - probably want to fix that?

**Comment by octonato** [comment]
> Do you mean like [this one](https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/java-customer-registry-kafka-quickstart/kafka/docker-compose.yml?rgh-link-date=2022-05-13T16%3A39%3A11Z)? or something else?

Yes. So we have it already. 

We can maybe move it out of the `kafka` folder to make it more visible and directly accessible? 

`mv kafka/docker-compose.yml docker-compose.yml`

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
@raboof, I think the best to do in this sample, is to move the `mv kafka/docker-compose.yml docker-compose.yml` and adapt the README. We don't need the docker to be inside `kafka` folder.

**Comment by franciscolopezsancho** [comment]
superseded by https://github.com/lightbend/kalix-jvm-sdk/pull/1142

**Pull request closed without merging**
