### PR TITLE
bump: kalix-proxy 1.0.2

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Comment by franciscolopezsancho** [comment]
I can see it's failing for the tck-tests. Once [this](https://github.com/lightbend/kalix-jvm-sdk/pull/932) is merged they will succeed.

**Review by jrudolph — APPROVED** [review]
LGTM, but let's rebase after #932 is done

**Comment by franciscolopezsancho** [comment]
#932 is done

**Comment by octonato** [comment]
Rebased!

**Pull request merged**
