### PR TITLE
bump: update proxy to 1.0.14

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Review by raboof — COMMENTED** [review]
I thought we don't want to update the version of the proxy used in the SDK (and samples) before that version of the proxy had made it to prod, and according to https://lightbendcloud.grafana.net/d/2n4jVuw7z/prod-kalix-metrics?orgId=1 prod is still on 1.0.12.

If we're really sure there is no risk that the SDK would use proxy features that are new in 1.0.14 then we could merge this already - but in that case perhaps there's no urgent need to?

**Comment by octonato** [comment]
You are right, I will close this one to avoid accidental merges. 

We do need it on the spring sdk branch, so I will open another PR for it.

**Comment by octonato** [comment]
Btw, we updated it already to 1.0.13 in #1049. 

It's hard to say if that's a problem or not. Same for the 1.0.14.

**Review by johanandren — APPROVED** [review]

**Comment by pvlugter** [comment]
It should usually be fine to have the updates slightly out-of-sync, given protocol compatibility. Things shouldn't break for a protocol addition, with default values on one side, ignored unknown fields on the other, although a new feature may not do anything until the proxy is updated.

**Pull request merged**
