### PR TITLE
feat(codegen): avoid touching regenerated files if nothing has changed

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
nice

**Comment by jrudolph** [comment]
> Does it work when the file does not exist yet?

No :) But I hopefully now fixed it...

**Review by pvlugter — APPROVED** [review]

**Comment by jrudolph** [comment]
Btw. the purpose behind this was to speed up subsequent maven builds which otherwise recompile everything all the time. Turns out, maven still recompiles everything if only a single source file changed, so this change only helps a bit. However, you can turn on incremental compilation in maven using:

```
-Dmaven.compiler.useIncrementalCompilation=false
```

And yes, `false`actually turns incremental compilation on (see https://issues.apache.org/jira/browse/MCOMPILER-209).

**Pull request merged**
